# Generated by Django 3.2.7 on 2021-09-08 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('note', models.IntegerField(default=0)),
                ('images', models.ImageField(upload_to='static')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('note', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=2000)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.path')),
            ],
        ),
    ]
