# Generated by Django 3.2.7 on 2021-09-09 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='images',
        ),
        migrations.RemoveField(
            model_name='path',
            name='note',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.path')),
            ],
        ),
    ]
