# Generated by Django 3.2.7 on 2021-09-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210910_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='path',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
